# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SILD.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(777, 581)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../iconosSILD/iconSILD.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.tabWidget_ = QtGui.QTabWidget(Dialog)
        self.tabWidget_.setGeometry(QtCore.QRect(0, 10, 771, 561))
        self.tabWidget_.setObjectName(_fromUtf8("tabWidget_"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 40, 661, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setWordWrap(False)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(170, 170, 111, 151))
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setPixmap(QtGui.QPixmap(_fromUtf8("../iconosSILD/labdental1.jpg")))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(570, 120, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(470, 150, 261, 181))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(110, 410, 521, 131))
        self.label_8.setText(_fromUtf8(""))
        self.label_8.setPixmap(QtGui.QPixmap(_fromUtf8("../iconosSILD/logo.PNG")))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.line_4 = QtGui.QFrame(self.tab)
        self.line_4.setGeometry(QtCore.QRect(400, 130, 20, 221))
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.tabWidget_.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox = QtGui.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 741, 81))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lineEditGuardarNombreProducto = QtGui.QLineEdit(self.groupBox)
        self.lineEditGuardarNombreProducto.setGeometry(QtCore.QRect(110, 20, 113, 20))
        self.lineEditGuardarNombreProducto.setObjectName(_fromUtf8("lineEditGuardarNombreProducto"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(250, 20, 81, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.pushButton_GuardarProducto = QtGui.QPushButton(self.groupBox)
        self.pushButton_GuardarProducto.setGeometry(QtCore.QRect(500, 20, 75, 23))
        self.pushButton_GuardarProducto.setObjectName(_fromUtf8("pushButton_GuardarProducto"))
        self.lineEditGuardarValorProductoo = QtGui.QLineEdit(self.groupBox)
        self.lineEditGuardarValorProductoo.setGeometry(QtCore.QRect(350, 20, 113, 20))
        self.lineEditGuardarValorProductoo.setObjectName(_fromUtf8("lineEditGuardarValorProductoo"))
        self.pushButton_2 = QtGui.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(500, 50, 75, 23))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.crearProducto = QtGui.QLabel(self.groupBox)
        self.crearProducto.setGeometry(QtCore.QRect(10, 50, 441, 20))
        self.crearProducto.setText(_fromUtf8(""))
        self.crearProducto.setObjectName(_fromUtf8("crearProducto"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 90, 741, 81))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.lineEditGuardarNombreInsumo = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditGuardarNombreInsumo.setGeometry(QtCore.QRect(110, 20, 113, 20))
        self.lineEditGuardarNombreInsumo.setObjectName(_fromUtf8("lineEditGuardarNombreInsumo"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(250, 20, 81, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.lineEditGuardarHorasInsumo = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditGuardarHorasInsumo.setGeometry(QtCore.QRect(350, 20, 113, 20))
        self.lineEditGuardarHorasInsumo.setObjectName(_fromUtf8("lineEditGuardarHorasInsumo"))
        self.pushButton_GuardarInusmo = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_GuardarInusmo.setGeometry(QtCore.QRect(500, 20, 75, 23))
        self.pushButton_GuardarInusmo.setObjectName(_fromUtf8("pushButton_GuardarInusmo"))
        self.pushButton_4 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_4.setGeometry(QtCore.QRect(500, 50, 75, 23))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.CrearInsumo = QtGui.QLabel(self.groupBox_2)
        self.CrearInsumo.setGeometry(QtCore.QRect(10, 50, 461, 20))
        self.CrearInsumo.setText(_fromUtf8(""))
        self.CrearInsumo.setObjectName(_fromUtf8("CrearInsumo"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 170, 741, 91))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.lineEditGuardarNombreUsuario = QtGui.QLineEdit(self.groupBox_3)
        self.lineEditGuardarNombreUsuario.setGeometry(QtCore.QRect(110, 20, 113, 20))
        self.lineEditGuardarNombreUsuario.setObjectName(_fromUtf8("lineEditGuardarNombreUsuario"))
        self.lineEdit_6 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_6.setGeometry(QtCore.QRect(360, 20, 113, 20))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.pushButtonGuardarUsuario = QtGui.QPushButton(self.groupBox_3)
        self.pushButtonGuardarUsuario.setGeometry(QtCore.QRect(490, 20, 75, 23))
        self.pushButtonGuardarUsuario.setObjectName(_fromUtf8("pushButtonGuardarUsuario"))
        self.pushButton_6 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_6.setGeometry(QtCore.QRect(490, 50, 75, 23))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.lineEditGuardarApellidoUsuario = QtGui.QLineEdit(self.groupBox_3)
        self.lineEditGuardarApellidoUsuario.setGeometry(QtCore.QRect(110, 50, 113, 20))
        self.lineEditGuardarApellidoUsuario.setObjectName(_fromUtf8("lineEditGuardarApellidoUsuario"))
        self.dateEditFEchaNacimientoUsuario = QtGui.QDateEdit(self.groupBox_3)
        self.dateEditFEchaNacimientoUsuario.setGeometry(QtCore.QRect(360, 50, 110, 22))
        self.dateEditFEchaNacimientoUsuario.setObjectName(_fromUtf8("dateEditFEchaNacimientoUsuario"))
        self.label_12 = QtGui.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(10, 50, 46, 13))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(240, 20, 111, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(240, 50, 101, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.Crearusuario = QtGui.QLabel(self.groupBox_3)
        self.Crearusuario.setGeometry(QtCore.QRect(10, 70, 691, 16))
        self.Crearusuario.setText(_fromUtf8(""))
        self.Crearusuario.setObjectName(_fromUtf8("Crearusuario"))
        self.groupBox_10 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 270, 741, 101))
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.label_21 = QtGui.QLabel(self.groupBox_10)
        self.label_21.setGeometry(QtCore.QRect(20, 30, 81, 16))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.lineEditAgregarActividad = QtGui.QLineEdit(self.groupBox_10)
        self.lineEditAgregarActividad.setGeometry(QtCore.QRect(110, 30, 113, 20))
        self.lineEditAgregarActividad.setObjectName(_fromUtf8("lineEditAgregarActividad"))
        self.label_22 = QtGui.QLabel(self.groupBox_10)
        self.label_22.setGeometry(QtCore.QRect(240, 10, 51, 16))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_23 = QtGui.QLabel(self.groupBox_10)
        self.label_23.setGeometry(QtCore.QRect(380, 10, 61, 16))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(self.groupBox_10)
        self.label_24.setGeometry(QtCore.QRect(540, 10, 151, 16))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.pushButtonGuardarActividad = QtGui.QPushButton(self.groupBox_10)
        self.pushButtonGuardarActividad.setGeometry(QtCore.QRect(190, 60, 75, 23))
        self.pushButtonGuardarActividad.setObjectName(_fromUtf8("pushButtonGuardarActividad"))
        self.pushButton_20 = QtGui.QPushButton(self.groupBox_10)
        self.pushButton_20.setGeometry(QtCore.QRect(300, 60, 75, 23))
        self.pushButton_20.setObjectName(_fromUtf8("pushButton_20"))
        self.CrearActividad = QtGui.QLabel(self.groupBox_10)
        self.CrearActividad.setGeometry(QtCore.QRect(10, 80, 621, 20))
        self.CrearActividad.setText(_fromUtf8(""))
        self.CrearActividad.setObjectName(_fromUtf8("CrearActividad"))
        self.lineEdit = QtGui.QLineEdit(self.groupBox_10)
        self.lineEdit.setGeometry(QtCore.QRect(240, 30, 113, 20))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox_10)
        self.lineEdit_2.setGeometry(QtCore.QRect(370, 30, 113, 20))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lineEdit_7 = QtGui.QLineEdit(self.groupBox_10)
        self.lineEdit_7.setGeometry(QtCore.QRect(540, 30, 151, 20))
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.pushButton_MostrarCrear = QtGui.QPushButton(self.groupBox_10)
        self.pushButton_MostrarCrear.setGeometry(QtCore.QRect(400, 60, 91, 23))
        self.pushButton_MostrarCrear.setObjectName(_fromUtf8("pushButton_MostrarCrear"))
        self.tableWidget__MostrarCrear = QtGui.QTableWidget(self.tab_2)
        self.tableWidget__MostrarCrear.setGeometry(QtCore.QRect(10, 380, 741, 151))
        self.tableWidget__MostrarCrear.setObjectName(_fromUtf8("tableWidget__MostrarCrear"))
        self.tableWidget__MostrarCrear.setColumnCount(0)
        self.tableWidget__MostrarCrear.setRowCount(0)
        self.tabWidget_.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 90, 741, 81))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.label_18 = QtGui.QLabel(self.groupBox_5)
        self.label_18.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.lineEditActualizarNombreInsumo = QtGui.QLineEdit(self.groupBox_5)
        self.lineEditActualizarNombreInsumo.setGeometry(QtCore.QRect(110, 20, 113, 20))
        self.lineEditActualizarNombreInsumo.setObjectName(_fromUtf8("lineEditActualizarNombreInsumo"))
        self.lineEditActualizarHorasInsumo = QtGui.QLineEdit(self.groupBox_5)
        self.lineEditActualizarHorasInsumo.setGeometry(QtCore.QRect(360, 20, 113, 20))
        self.lineEditActualizarHorasInsumo.setObjectName(_fromUtf8("lineEditActualizarHorasInsumo"))
        self.pushButton_ActualizarInsumo = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_ActualizarInsumo.setGeometry(QtCore.QRect(660, 20, 75, 23))
        self.pushButton_ActualizarInsumo.setObjectName(_fromUtf8("pushButton_ActualizarInsumo"))
        self.pushButton_10 = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_10.setGeometry(QtCore.QRect(660, 50, 75, 23))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.label_20 = QtGui.QLabel(self.groupBox_5)
        self.label_20.setGeometry(QtCore.QRect(240, 20, 111, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_35 = QtGui.QLabel(self.groupBox_5)
        self.label_35.setGeometry(QtCore.QRect(480, 20, 46, 13))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.lineEdit_IDACtualizarInsumo = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_IDACtualizarInsumo.setGeometry(QtCore.QRect(530, 20, 113, 20))
        self.lineEdit_IDACtualizarInsumo.setObjectName(_fromUtf8("lineEdit_IDACtualizarInsumo"))
        self.ModificarInsumo = QtGui.QLabel(self.groupBox_5)
        self.ModificarInsumo.setGeometry(QtCore.QRect(10, 60, 641, 20))
        self.ModificarInsumo.setText(_fromUtf8(""))
        self.ModificarInsumo.setObjectName(_fromUtf8("ModificarInsumo"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 180, 741, 91))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.label_26 = QtGui.QLabel(self.groupBox_6)
        self.label_26.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.lineEditActualizarNombreUsuario = QtGui.QLineEdit(self.groupBox_6)
        self.lineEditActualizarNombreUsuario.setGeometry(QtCore.QRect(110, 20, 113, 20))
        self.lineEditActualizarNombreUsuario.setObjectName(_fromUtf8("lineEditActualizarNombreUsuario"))
        self.lineEditActualizarApellidoUsuaio = QtGui.QLineEdit(self.groupBox_6)
        self.lineEditActualizarApellidoUsuaio.setGeometry(QtCore.QRect(110, 50, 113, 20))
        self.lineEditActualizarApellidoUsuaio.setObjectName(_fromUtf8("lineEditActualizarApellidoUsuaio"))
        self.label_27 = QtGui.QLabel(self.groupBox_6)
        self.label_27.setGeometry(QtCore.QRect(10, 43, 41, 20))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_29 = QtGui.QLabel(self.groupBox_6)
        self.label_29.setGeometry(QtCore.QRect(240, 20, 101, 16))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.lineEditActualizarFechaNacUsuario = QtGui.QLineEdit(self.groupBox_6)
        self.lineEditActualizarFechaNacUsuario.setGeometry(QtCore.QRect(360, 20, 113, 20))
        self.lineEditActualizarFechaNacUsuario.setObjectName(_fromUtf8("lineEditActualizarFechaNacUsuario"))
        self.pushButton_14 = QtGui.QPushButton(self.groupBox_6)
        self.pushButton_14.setGeometry(QtCore.QRect(660, 40, 75, 23))
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.pushButton_ActualizarUsuario = QtGui.QPushButton(self.groupBox_6)
        self.pushButton_ActualizarUsuario.setGeometry(QtCore.QRect(660, 10, 75, 23))
        self.pushButton_ActualizarUsuario.setObjectName(_fromUtf8("pushButton_ActualizarUsuario"))
        self.label_36 = QtGui.QLabel(self.groupBox_6)
        self.label_36.setGeometry(QtCore.QRect(480, 20, 51, 16))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.lineEdit_idActualizarUsuario = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_idActualizarUsuario.setGeometry(QtCore.QRect(540, 20, 113, 20))
        self.lineEdit_idActualizarUsuario.setObjectName(_fromUtf8("lineEdit_idActualizarUsuario"))
        self.ModificarUsuario = QtGui.QLabel(self.groupBox_6)
        self.ModificarUsuario.setGeometry(QtCore.QRect(10, 70, 721, 16))
        self.ModificarUsuario.setText(_fromUtf8(""))
        self.ModificarUsuario.setObjectName(_fromUtf8("ModificarUsuario"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 741, 71))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.label_14 = QtGui.QLabel(self.groupBox_4)
        self.label_14.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.lineEditActualizarNombreProducto = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditActualizarNombreProducto.setGeometry(QtCore.QRect(110, 20, 113, 20))
        self.lineEditActualizarNombreProducto.setObjectName(_fromUtf8("lineEditActualizarNombreProducto"))
        self.lineEditActualizarValorProducto = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditActualizarValorProducto.setGeometry(QtCore.QRect(340, 20, 113, 20))
        self.lineEditActualizarValorProducto.setObjectName(_fromUtf8("lineEditActualizarValorProducto"))
        self.label_15 = QtGui.QLabel(self.groupBox_4)
        self.label_15.setGeometry(QtCore.QRect(240, 20, 71, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.pushButton_8 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_8.setGeometry(QtCore.QRect(660, 40, 75, 23))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.pushButton_ActualizarProducto = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_ActualizarProducto.setGeometry(QtCore.QRect(660, 10, 75, 23))
        self.pushButton_ActualizarProducto.setObjectName(_fromUtf8("pushButton_ActualizarProducto"))
        self.label_34 = QtGui.QLabel(self.groupBox_4)
        self.label_34.setGeometry(QtCore.QRect(470, 20, 61, 16))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.lineEdit_IDActualizarProducto = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_IDActualizarProducto.setGeometry(QtCore.QRect(530, 20, 113, 20))
        self.lineEdit_IDActualizarProducto.setObjectName(_fromUtf8("lineEdit_IDActualizarProducto"))
        self.ModificarProducto = QtGui.QLabel(self.groupBox_4)
        self.ModificarProducto.setGeometry(QtCore.QRect(10, 50, 631, 16))
        self.ModificarProducto.setText(_fromUtf8(""))
        self.ModificarProducto.setObjectName(_fromUtf8("ModificarProducto"))
        self.groupBox_11 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_11.setGeometry(QtCore.QRect(10, 280, 741, 111))
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.label_25 = QtGui.QLabel(self.groupBox_11)
        self.label_25.setGeometry(QtCore.QRect(20, 30, 81, 16))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.lineEditAgregarActividad_2 = QtGui.QLineEdit(self.groupBox_11)
        self.lineEditAgregarActividad_2.setGeometry(QtCore.QRect(110, 30, 113, 20))
        self.lineEditAgregarActividad_2.setObjectName(_fromUtf8("lineEditAgregarActividad_2"))
        self.label_28 = QtGui.QLabel(self.groupBox_11)
        self.label_28.setGeometry(QtCore.QRect(240, 10, 46, 13))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_30 = QtGui.QLabel(self.groupBox_11)
        self.label_30.setGeometry(QtCore.QRect(380, 10, 46, 13))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_31 = QtGui.QLabel(self.groupBox_11)
        self.label_31.setGeometry(QtCore.QRect(540, 10, 151, 16))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.pushButtonGuardarActividad_2 = QtGui.QPushButton(self.groupBox_11)
        self.pushButtonGuardarActividad_2.setGeometry(QtCore.QRect(280, 60, 75, 23))
        self.pushButtonGuardarActividad_2.setObjectName(_fromUtf8("pushButtonGuardarActividad_2"))
        self.pushButton_21 = QtGui.QPushButton(self.groupBox_11)
        self.pushButton_21.setGeometry(QtCore.QRect(370, 60, 75, 23))
        self.pushButton_21.setObjectName(_fromUtf8("pushButton_21"))
        self.label_37 = QtGui.QLabel(self.groupBox_11)
        self.label_37.setGeometry(QtCore.QRect(20, 60, 71, 16))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.lineEdit_IdActualizarActividad = QtGui.QLineEdit(self.groupBox_11)
        self.lineEdit_IdActualizarActividad.setGeometry(QtCore.QRect(110, 60, 113, 20))
        self.lineEdit_IdActualizarActividad.setObjectName(_fromUtf8("lineEdit_IdActualizarActividad"))
        self.ActualizarActividad = QtGui.QLabel(self.groupBox_11)
        self.ActualizarActividad.setGeometry(QtCore.QRect(10, 90, 711, 16))
        self.ActualizarActividad.setText(_fromUtf8(""))
        self.ActualizarActividad.setObjectName(_fromUtf8("ActualizarActividad"))
        self.lineEdit_3 = QtGui.QLineEdit(self.groupBox_11)
        self.lineEdit_3.setGeometry(QtCore.QRect(240, 30, 113, 20))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.lineEdit_4 = QtGui.QLineEdit(self.groupBox_11)
        self.lineEdit_4.setGeometry(QtCore.QRect(380, 30, 113, 20))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.lineEdit_5 = QtGui.QLineEdit(self.groupBox_11)
        self.lineEdit_5.setGeometry(QtCore.QRect(540, 30, 113, 20))
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.pushButton_MostrarActualizar = QtGui.QPushButton(self.groupBox_11)
        self.pushButton_MostrarActualizar.setGeometry(QtCore.QRect(460, 60, 81, 23))
        self.pushButton_MostrarActualizar.setObjectName(_fromUtf8("pushButton_MostrarActualizar"))
        self.tableWidget_MostrarDatos = QtGui.QTableWidget(self.tab_3)
        self.tableWidget_MostrarDatos.setGeometry(QtCore.QRect(10, 400, 741, 131))
        self.tableWidget_MostrarDatos.setObjectName(_fromUtf8("tableWidget_MostrarDatos"))
        self.tableWidget_MostrarDatos.setColumnCount(0)
        self.tableWidget_MostrarDatos.setRowCount(0)
        self.tabWidget_.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.tableWidget = QtGui.QTableWidget(self.tab_4)
        self.tableWidget.setGeometry(QtCore.QRect(10, 200, 751, 331))
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.groupBox_7 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 10, 231, 81))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.pushButton_MostrarAllProducts = QtGui.QPushButton(self.groupBox_7)
        self.pushButton_MostrarAllProducts.setGeometry(QtCore.QRect(10, 30, 211, 31))
        self.pushButton_MostrarAllProducts.setObjectName(_fromUtf8("pushButton_MostrarAllProducts"))
        self.groupBox_8 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_8.setGeometry(QtCore.QRect(520, 10, 221, 81))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.pushButton_ShowAllInsumos = QtGui.QPushButton(self.groupBox_8)
        self.pushButton_ShowAllInsumos.setGeometry(QtCore.QRect(10, 30, 201, 31))
        self.pushButton_ShowAllInsumos.setObjectName(_fromUtf8("pushButton_ShowAllInsumos"))
        self.groupBox_9 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_9.setGeometry(QtCore.QRect(250, 10, 241, 81))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.pushButton_ShowAllUsers = QtGui.QPushButton(self.groupBox_9)
        self.pushButton_ShowAllUsers.setGeometry(QtCore.QRect(10, 30, 221, 31))
        self.pushButton_ShowAllUsers.setObjectName(_fromUtf8("pushButton_ShowAllUsers"))
        self.groupBox_12 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_12.setGeometry(QtCore.QRect(10, 100, 211, 81))
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        #self.pushButton = QtGui.QPushButton(self.groupBox_12)
        #self.pushButton.setGeometry(QtCore.QRect(20, 20, 91, 51))
        #self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_5 = QtGui.QPushButton(self.groupBox_12)
        self.pushButton_5.setGeometry(QtCore.QRect(130, 30, 75, 23))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.line = QtGui.QFrame(self.tab_4)
        self.line.setGeometry(QtCore.QRect(20, 90, 221, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.tab_4)
        self.line_2.setGeometry(QtCore.QRect(250, 90, 241, 21))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.tabWidget_.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.label_33 = QtGui.QLabel(self.tab_5)
        self.label_33.setGeometry(QtCore.QRect(30, 30, 170, 16))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.pushButton_7 = QtGui.QPushButton(self.tab_5)
        self.pushButton_7.setGeometry(QtCore.QRect(30, 70, 131, 23))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.tabWidget_.addTab(self.tab_5, _fromUtf8(""))

        self.retranslateUi(Dialog)
        self.tabWidget_.setCurrentIndex(0)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineEditGuardarValorProductoo.clear)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineEditGuardarNombreProducto.clear)
        QtCore.QObject.connect(self.pushButton_6, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineEditGuardarApellidoUsuario.clear)
        QtCore.QObject.connect(self.pushButton_6, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineEditGuardarNombreUsuario.clear)
        QtCore.QObject.connect(self.pushButton_4, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineEditGuardarHorasInsumo.clear)
        QtCore.QObject.connect(self.pushButton_4, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineEditGuardarNombreInsumo.clear)
        QtCore.QObject.connect(self.pushButton_6, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineEdit_6.clear)
        QtCore.QObject.connect(self.pushButton_6, QtCore.SIGNAL(_fromUtf8("clicked()")), self.dateEditFEchaNacimientoUsuario.clear)
        QtCore.QObject.connect(self.pushButton_8, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineEditActualizarValorProducto.clear)
        QtCore.QObject.connect(self.pushButton_8, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineEditActualizarNombreProducto.clear)
        QtCore.QObject.connect(self.pushButton_10, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineEditActualizarNombreInsumo.clear)
        QtCore.QObject.connect(self.pushButton_10, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineEditActualizarHorasInsumo.clear)
        QtCore.QObject.connect(self.pushButton_14, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineEditActualizarNombreUsuario.clear)
        QtCore.QObject.connect(self.pushButton_14, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineEditActualizarApellidoUsuaio.clear)
        QtCore.QObject.connect(self.pushButton_20, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineEditAgregarActividad.clear)
        QtCore.QObject.connect(self.pushButton_21, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineEditAgregarActividad_2.clear)
        QtCore.QObject.connect(self.pushButton_14, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineEditActualizarFechaNacUsuario.clear)
        QtCore.QObject.connect(self.pushButton_14, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineEdit_idActualizarUsuario.clear)
        QtCore.QObject.connect(self.pushButton_21, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineEdit_IdActualizarActividad.clear)
        QtCore.QObject.connect(self.pushButton_10, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineEdit_IDACtualizarInsumo.clear)
        QtCore.QObject.connect(self.pushButton_8, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineEdit_IDActualizarProducto.clear)
        QtCore.QObject.connect(self.pushButton_MostrarAllProducts, QtCore.SIGNAL(_fromUtf8("clicked()")), self.tableWidget.clear)
        QtCore.QObject.connect(self.pushButton_ShowAllUsers, QtCore.SIGNAL(_fromUtf8("clicked()")), self.tableWidget.clear)
        QtCore.QObject.connect(self.pushButton_ShowAllInsumos, QtCore.SIGNAL(_fromUtf8("clicked()")), self.tableWidget.clear)
        #QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.tableWidget.clear)
        QtCore.QObject.connect(self.pushButton_5, QtCore.SIGNAL(_fromUtf8("clicked()")), self.tableWidget.clear)
        QtCore.QObject.connect(self.pushButton_MostrarCrear, QtCore.SIGNAL(_fromUtf8("clicked()")), self.tableWidget__MostrarCrear.clear)
        QtCore.QObject.connect(self.pushButton_MostrarActualizar, QtCore.SIGNAL(_fromUtf8("clicked()")), self.tableWidget_MostrarDatos.clear)
        QtCore.QObject.connect(self.pushButton_20, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineEdit.clear)
        QtCore.QObject.connect(self.pushButton_20, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineEdit_2.clear)
        QtCore.QObject.connect(self.pushButton_20, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lineEdit_7.clear)
        QtCore.QObject.connect(self.pushButton_20, QtCore.SIGNAL(_fromUtf8("clicked()")), self.CrearActividad.clear)
        QtCore.QObject.connect(self.pushButton_6, QtCore.SIGNAL(_fromUtf8("clicked()")), self.Crearusuario.clear)
        QtCore.QObject.connect(self.pushButton_4, QtCore.SIGNAL(_fromUtf8("clicked()")), self.CrearInsumo.clear)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), self.crearProducto.clear)

        QtCore.QObject.connect(self.pushButton_10, QtCore.SIGNAL(_fromUtf8("clicked()")), self.ModificarInsumo.clear)
        QtCore.QObject.connect(self.pushButton_8, QtCore.SIGNAL(_fromUtf8("clicked()")), self.ModificarProducto.clear)
        QtCore.QObject.connect(self.pushButton_14, QtCore.SIGNAL(_fromUtf8("clicked()")), self.ModificarUsuario.clear)
        QtCore.QObject.connect(self.pushButton_21, QtCore.SIGNAL(_fromUtf8("clicked()")), self.ActualizarActividad.clear)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Sistema de Información Laboratorio Dental (SILD)", None))
        self.label.setText(_translate("Dialog", "Sistema de Información Laboratorio Dental \n"
"                              (SILD)", None))
        self.label_3.setText(_translate("Dialog", "Realizado por:", None))
        self.label_4.setText(_translate("Dialog", "      Arnold Julian Herrera Quiñones - 625569 \n"
"  \n"
"         Cristhian Camilo Arce García - 625577 \n"
"\n"
"                         Presentado a: \n"
" \n"
"               Roger Enrique Guzman Avendaño \n"
" \n"
"                               Materia: \n"
" \n"
"               Investigacion de Operaciones", None))
        self.tabWidget_.setTabText(self.tabWidget_.indexOf(self.tab), _translate("Dialog", "Inicio", None))
        self.groupBox.setTitle(_translate("Dialog", "&Crear Producto", None))
        self.label_5.setText(_translate("Dialog", "Nombre Producto", None))
        self.label_6.setText(_translate("Dialog", "Valor Producto", None))
        self.pushButton_GuardarProducto.setText(_translate("Dialog", "&Guardar", None))
        self.pushButton_2.setText(_translate("Dialog", "&Borrar", None))
        self.groupBox_2.setTitle(_translate("Dialog", "&Crear Insumo", None))
        self.label_7.setText(_translate("Dialog", "Nombre Insumo", None))
        self.label_9.setText(_translate("Dialog", "Horas Disponibles", None))
        self.pushButton_GuardarInusmo.setText(_translate("Dialog", "&Guardar", None))
        self.pushButton_4.setText(_translate("Dialog", "&Borrar", None))
        self.groupBox_3.setTitle(_translate("Dialog", "Crear Usuario", None))
        self.label_10.setText(_translate("Dialog", "Nombre ", None))
        self.pushButtonGuardarUsuario.setText(_translate("Dialog", "&Guardar", None))
        self.pushButton_6.setText(_translate("Dialog", "&Borrar", None))
        self.label_12.setText(_translate("Dialog", "Apellido", None))
        self.label_11.setText(_translate("Dialog", "Cédula de Ciudadanía", None))
        self.label_13.setText(_translate("Dialog", "Fecha de Nacimiento", None))
        self.groupBox_10.setTitle(_translate("Dialog", "&Actividad", None))
        self.label_21.setText(_translate("Dialog", "Horas Actividad", None))
        self.label_22.setText(_translate("Dialog", "Id Insumo", None))
        self.label_23.setText(_translate("Dialog", "IdProducto", None))
        self.label_24.setText(_translate("Dialog", "Usuario que hace la actividad", None))
        self.pushButtonGuardarActividad.setText(_translate("Dialog", "&Guardar", None))
        self.pushButton_20.setText(_translate("Dialog", "&Borrar", None))
        self.pushButton_MostrarCrear.setText(_translate("Dialog", "Mostrar Datos", None))
        self.tabWidget_.setTabText(self.tabWidget_.indexOf(self.tab_2), _translate("Dialog", "Crear", None))
        self.groupBox_5.setTitle(_translate("Dialog", "Modificar Insumo", None))
        self.label_18.setText(_translate("Dialog", "Nombre Insumo", None))
        self.pushButton_ActualizarInsumo.setText(_translate("Dialog", "&Guardar", None))
        self.pushButton_10.setText(_translate("Dialog", "&Borrar", None))
        self.label_20.setText(_translate("Dialog", "Horas disponibles", None))
        self.label_35.setText(_translate("Dialog", "Id Insumo", None))
        self.groupBox_6.setTitle(_translate("Dialog", "Modificar Usuario", None))
        self.label_26.setText(_translate("Dialog", "Nombre ", None))
        self.label_27.setText(_translate("Dialog", "Apellido", None))
        self.label_29.setText(_translate("Dialog", "Fecha de Nacimiento", None))
        self.pushButton_14.setText(_translate("Dialog", "&Borrar", None))
        self.pushButton_ActualizarUsuario.setText(_translate("Dialog", "&Guardar", None))
        self.label_36.setText(_translate("Dialog", "Cedula", None))
        self.groupBox_4.setTitle(_translate("Dialog", "Modificar Producto", None))
        self.label_14.setText(_translate("Dialog", "Nombre Producto", None))
        self.label_15.setText(_translate("Dialog", "Valor Producto", None))
        self.pushButton_8.setText(_translate("Dialog", "&Borrar", None))
        self.pushButton_ActualizarProducto.setText(_translate("Dialog", "&Guardar", None))
        self.label_34.setText(_translate("Dialog", "Id Producto", None))
        self.groupBox_11.setTitle(_translate("Dialog", "&Modificar Actividad", None))
        self.label_25.setText(_translate("Dialog", "Horas Actividad", None))
        self.label_28.setText(_translate("Dialog", "Id Insumo", None))
        self.label_30.setText(_translate("Dialog", "Id Producto", None))
        self.label_31.setText(_translate("Dialog", "Cedula Usuario que hace la actividad", None))
        self.pushButtonGuardarActividad_2.setText(_translate("Dialog", "&Guardar", None))
        self.pushButton_21.setText(_translate("Dialog", "&Borrar", None))
        self.label_37.setText(_translate("Dialog", "Id Actividad", None))
        self.pushButton_MostrarActualizar.setText(_translate("Dialog", "&Mostrar Datos", None))
        self.tabWidget_.setTabText(self.tabWidget_.indexOf(self.tab_3), _translate("Dialog", "Actualizar", None))
        self.groupBox_7.setTitle(_translate("Dialog", "Producto", None))
        self.pushButton_MostrarAllProducts.setText(_translate("Dialog", "&Mostrar Todos los \n"
" Productos", None))
        self.groupBox_8.setTitle(_translate("Dialog", "Insumo", None))
        self.pushButton_ShowAllInsumos.setText(_translate("Dialog", "&Mostrar Todos los \n"
" Insumos", None))
        self.groupBox_9.setTitle(_translate("Dialog", "Usuario", None))
        self.pushButton_ShowAllUsers.setText(_translate("Dialog", "&Mostrar Todos los \n"
" Usuarios", None))
        self.groupBox_12.setTitle(_translate("Dialog", "&Otras Busquedas", None))

        self.pushButton_5.setText(_translate("Dialog", "&Actividades", None))
        self.tabWidget_.setTabText(self.tabWidget_.indexOf(self.tab_4), _translate("Dialog", "Mostrar", None))
        self.label_33.setText(_translate("Dialog", "Ganancia = ", None))
        self.pushButton_7.setText(_translate("Dialog", "&Realizar Analisis", None))
        self.tabWidget_.setTabText(self.tabWidget_.indexOf(self.tab_5), _translate("Dialog", "Analisis", None))

